### PR TITLE
Proper benchmarking of regex

### PR DESCRIPTION
**Pull request by pczarn**

### CODE REVIEW

**Comment by pczarn** [comment]
Just now, I figured out this code is mostly pulled from the datetime library.

**Comment by pczarn** [comment]
Just now, I figured out this code is mostly pulled from the datetime library.

**Comment by pczarn** [comment]
Just now, I figured out this code is mostly pulled from the datetime library.

**Comment by hoodie** [comment]
I like those changes.
Could you make them an extra benchmark though?
That would allow better comparison.
Thanks

**update**
sorry, saw you did that :D

**Pull request merged**
